### ISSUE TITLE
Mover y volver principal el repositorio

### ISSUE THREAD

**Issue by grottas** [odooloco/l10n_co_e-invoice#2]
@odooloco/odooloco 

Movemos este repositorio a https://github.com/odooloco/l10n-colombia/ ?

Podemos hacer que sea el principal?

**Comment by hivam** [comment]
No tengo permisos, ya pedí que le asignen permisos a https://github.com/lauracvilla

**Comment by grottas** [comment]
Por favor pide autorización para @JoanMarin por parte de nuestro equipo
